### ISSUE TITLE
[feature discuss] add "git init" process in this program

### ISSUE THREAD

**Issue by weykon** [weykon/add-git-push-url#1]
when I create a new git repo ,  such as  - git init , - git add . , - git commit -m 'init' . I prefer to write a program to finish these command and add a console input or anything else to set the second git repo address .

**Comment by mingxuanzi** [comment]
?

**Comment by yuanluoyue** [comment]
> when I create a new git repo , such as - git init , - git add . , - git commit -m 'init' . I prefer to write a program to finish these command and add a console input or anything else to set the second git repo address .
you need cli, like vue-cli，it auto git init

**Comment by weykon** [comment]
so I try a cli code
